# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sebastian-meier.github.io/BerlinRefined" # http://127.0.0.1:4000

# Build settings
markdown: kramdown

#github: [metadata]
# kramdown:
#   input: GFM
#   hard_wrap: false
# gems:
#   - jekyll-coffeescript
#   - jekyll-paginate

#overwritten by github, no need to worry
lsi: false
safe: true
#source: [your repo's top level directory]
incremental: false
#highlighter: rouge
#gist:
#noscript: false

exclude: [data]
